
type Figures = {
    id: number,
        image:string,
        MC:String,
        type:string,
        Anime:String,
        Height:String,
        Instock:boolean,
       StockNum:number,
       Outstock:number,
        price:number,
        Shipment:String;
        Figurenotes:string;
        timestamp: number;
  };
  
  export const FiguresData = [
      {
        id: 1,
        image: "/home_img/naruto.jpg",
        MC:"Naruto",
        type:"Standing Figure",
        Anime:"Naruto",
        Height:"125cm",
        Instock:true,
       StockNum:1,
       Outstock:0,
        price:1300,
        Figurenotes:"O2t02u52r26a20N125",
        Shipment:"1-3 weeks",
        timestamp: 1740575740,
      },
      {
        id: 2,
        image: "/home_img/hinata.jpg",
        MC:"Hinata",
        type:"Standing Figure",
        Anime:"Naruto",
        Height:"120cm",
        Instock:true,
       StockNum:3,
       Outstock:0,
        price:2000,
        Figurenotes:"A2t02a52n26i21H120",
        Shipment:"1-3 weeks",
        timestamp: 1740575720,
      },
      {
        id: 3,
        image: "/home_img/jotaro.jpg",
        type:"Standing Figure",
        MC:"Jotaro",
        Anime:"JoJo",
        Height:"105cm",
        Instock:false,
       StockNum:0,
       Outstock:0,
        price:1500,
        Figurenotes:"O2r02a52t26o219J105",
        Shipment:"1-3 weeks",
        timestamp: 1740575840,
      },
      {
        id: 4,
        image: "/home_img/Ino.jpg",
        type:"Standing Figure",
        MC:"Ino",
        Anime:"Naruto",
        Height:"125cm",
        Instock:false,
       StockNum:0,
       Outstock:0,
        price:1000,
        Figurenotes:"O2n02I522620125",
        Shipment:"1-3 weeks",
        timestamp: 1740575741,
      },
      {
        id: 5,
        image: "/home_img/Gojo.jpg",
        type:"Standing Figure",
        MC:"Gojo",
        Anime:"JuJutsu Kaisen",
        Height:"125cm",
        Instock:false,
       StockNum:0,
       Outstock:0,
        price:2100,
        Figurenotes:"O2j02o52G2620125",
        Shipment:"1-3 weeks",
        timestamp: 1740575750,
      },
      {
        id: 6,
        image: "/home_img/SoloSung.jpg",
        type:"Standing Figure",
        MC:"Sung Jin-Woo",
        Anime:"Solo leveling",
        Height:"125cm",
        Instock:false,
       StockNum:0,
       Outstock:0,
        price:2100,
        Figurenotes:"O2t02u52r26a20N125",
        Shipment:"1-3 weeks",
        timestamp: 1740575747,
      },
      {
        id: 7,
        image: "/home_img/naruto_9tails.jpg",
        type:"Standing Figure",
        MC:"Naruto",
        Anime:"Naruto",
        Height:"125cm",
        Instock:false,
       StockNum:0,
       Outstock:0,
        price:2200,
        timestamp: 1740575748,
        Shipment:"1-3 weeks",
        Figurenotes:"O2t02u52r26a20N125",
      },
      {
        id: 8,
        image: "/home_img/naruto_clone.jpg",
        MC:"Naruto",
        type:"Standing Figure",
        Anime:"Naruto",
        Height:"125cm",
        Instock:false,
       StockNum:0,
       Outstock:0,
        price:2200,
        timestamp: 1740575744,
        Shipment:"1-3 weeks",
        Figurenotes:"O2t02u52r26a20N125",
      },
      {
        id: 9,
        image: "/home_img/anime-attack-on-titan-keychain-key-chain-ring-glow-in-dark.png",
        MC:"Wing of Freedom",
        type:"keyChain",
        Anime:"Attack On Titan",
        Height:"20cm",
        Instock:true,
       StockNum:10,
       Outstock:0,
        price:120,
        timestamp: 1740723157,
        Shipment:"1-3 weeks",
        Figurenotes:"713192-10-25202",
      },
      {
        id: 10,
        image: "/home_img/gojo_chibi.jpg",
        MC:"Gojo",
        type:"Chibi",
        Anime:"Jujutsu Kaisen",
        Height:"18cm",
        Instock:true,
       StockNum:10,
       Outstock:0,
        price:140,
        timestamp: 1740723246,
        Shipment:"1-3 weeks",
        Figurenotes:"613192-18-25202",
      },{
        id: 11,
        image: "/home_img/REBORN-Sky-Vongola-Ring.jpg",
        MC:"Vongola Sky Ring",
        type:"Ring",
        Anime:"Reborn",
        Height:"??",
        Instock:true,
       StockNum:20,
       Outstock:0,
        price:150,
        timestamp: 1740723456,
        Shipment:"1-3 weeks",
        Figurenotes:"513192-25202",
      },{
        id: 12,
        image: "/home_img/swordkeychain.png",
        MC:"Sword",
        type:"keyChain",
        Anime:"Demon Slayer",
        Height:"25cm",
        Instock:true,
       StockNum:7,
       Outstock:0,
        price:100,
        timestamp: 1740723360,
        Shipment:"1-3 weeks",
        Figurenotes:"413192-25-25202",
      }
    ];